server:
  port: 8081


spring:
  application:
    name: customer
  datasource:
    username: 'admin'
    url: jdbc:postgresql://localhost:5432/calendar
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'